services:
    convertra:
        container_name: convertra
        image: ghcr.io/vibecoder11200/convertra:latest
        build:
            context: .
            args:
                PUB_HOSTNAME: ${PUB_HOSTNAME:-localhost:5173}
                PUB_PLAUSIBLE_URL: ${PUB_PLAUSIBLE_URL:-}
                PUB_ENV: ${PUB_ENV:-production}
                PUB_DISABLE_ALL_EXTERNAL_REQUESTS: ${PUB_DISABLE_ALL_EXTERNAL_REQUESTS:-false}
                PUB_VERTD_URL: ${PUB_VERTD_URL:-}
                PUB_DONATION_URL: ${PUB_DONATION_URL:-}
                PUB_STRIPE_KEY: ${PUB_STRIPE_KEY:-}
        restart: unless-stopped
        ports:
            - ${PORT:-3000}:80
